baseurl: '/'
permalink: pretty
title: 'TAAS Technologies'

languages: ["vn", "en"]
exclude_from_localizations: ["javascript", "images", "css"]
defaultLang: en
languageNames:
  vn: Tiếng Việt
  en: English

logo:
  mobile: "images/logo/tass-technologies.png"
  # mobile_height: "32px"
  # mobile_width: "32px"
  desktop: "images/logo/tass-technologies.png"
  desktop-invert: "images/logo/tass-technologies-invert.png"
  # desktop_height: "48.57px"
  # desktop_width: "120px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables
  - jekyll-multiple-languages-plugin

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
